InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Controllers/AdminController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    
    public class AdminController : Controller
    {
        private InsuranceDbContext dbContext;
        public AdminController()
        {
            dbContext = new InsuranceDbContext(); //initialize your DbContext
        }
        // GET: Admin
        public ActionResult Dashboard()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                return View();
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }


        public ActionResult GetAllCustomers()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var customers = dbContext.Customers.ToList();
                return View(customers);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        //Action method to get all users
        public ActionResult GetAllUsers()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var users = dbContext.Customers.ToList();
                return View(users);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }


        public ActionResult PoliciesList()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var policies = dbContext.Policies.ToList();
                return View(policies);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult Categories()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var categories = dbContext.Categories.ToList();
                return View(categories);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult AllAppliedPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var appliedPolicies = dbContext.AppliedPolicies.ToList();
                return View(appliedPolicies);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }



        [HttpPost]
        public ActionResult ApprovePolicy(int policyId)
        {
            if (Session["AdminUserId"] != null)
            {
                var policy = dbContext.AppliedPolicies.Find(policyId);
                if (policy != null && policy.StatusCode == PolicyStatus.Pending)
                {
                    policy.StatusCode = PolicyStatus.Approved;
                    dbContext.SaveChanges();
                }
                return RedirectToAction("AllAppliedPolicies");
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        [HttpPost]
        public ActionResult DisapprovePolicy(int policyId)
        {
            if (Session["AdminUserId"] != null)
            {
                var policy = dbContext.AppliedPolicies.Find(policyId);
                if (policy != null && policy.StatusCode == PolicyStatus.Pending)
                {
                    policy.StatusCode = PolicyStatus.Disapproved;
                    dbContext.SaveChanges();
                }
                return RedirectToAction("AllAppliedPolicies");
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult ApprovedPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                var approvedPolicies = dbContext.AppliedPolicies.Where(p => p.StatusCode == PolicyStatus.Approved).ToList();
                return View(approvedPolicies);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult DisapprovedPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                var disapprovedPolicies = dbContext.AppliedPolicies.Where(p => p.StatusCode == PolicyStatus.Disapproved).ToList();
                return View(disapprovedPolicies);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult PendingPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                var pendingPolicies = dbContext.AppliedPolicies.Where(p => p.StatusCode == PolicyStatus.Pending).ToList();
                return View(pendingPolicies);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult Policy()
        {
            if (Session["AdminUserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }


        public ActionResult Question()
        {
            if (Session["AdminUserId"] != null)
            {
                var questions = dbContext.Questions.ToList();
                return View(questions);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult Reply(int id)
        {
            if (Session["AdminUserId"] != null)
            {
                var question = dbContext.Questions.Find(id);
                return View(question);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        [HttpPost]
        public ActionResult Reply(Questions model)
        {
            if (Session["AdminUserId"] != null && ModelState.IsValid)
            {
                var existingQuestion = dbContext.Questions.Find(model.QuestionId);
                if (existingQuestion != null)
                {
                    existingQuestion.Answer = model.Answer;
                    dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult SaveAnswer(int questionId, string answer)
        {
            if (Session["AdminUserId"] != null)
            {
                var existingQuestion = dbContext.Questions.Find(questionId);
                if (existingQuestion != null)
                {
                    existingQuestion.Answer = answer;
                    dbContext.SaveChanges();
                    return Json(new { success = true });
                }
            }

            return Json(new { success = false, error = "Question not found" });
        }


    }
}

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Controllers/CustomerController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Models;

namespace UI.Controllers
{
    public class CustomerController : Controller
    {
        
        private InsuranceDbContext dbContext;  
        public CustomerController()
        {
            dbContext = new InsuranceDbContext(); 
        }
        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);

            // Check if UserId is present in the session, otherwise redirect to login
            if (Session["CustomerUserId"] == null)
            {
                filterContext.Result = RedirectToAction("CustomerLogin", "Validation");
            }
        }

        public ActionResult Dashboard()  
        {
            return View();  
        }
        
        
        public ActionResult GetAllUsers()    
        {
            var user = dbContext.Customers.ToList(); 
            return View(user);
        }
        public ActionResult ViewPoliciesToApply()  
        {
            List<Policy> policies = dbContext.Policies.ToList();  
            return View(policies);
        }
        public ActionResult Apply(int policyId)  
        {
            int customerId = Convert.ToInt32(Session["CustomerUserId"]);
           
            bool AppliedAlready = dbContext.AppliedPolicies
            .Any(ap => ap.CustomerId == customerId && ap.AppliedPolicyId == policyId);
            if (!AppliedAlready)
            {
              
                Policy policy = dbContext.Policies.FirstOrDefault(p => p.PolicyId == policyId);

                if (policy != null)
                {
                   
                    AppliedPolicy appliedPolicy = new AppliedPolicy
                    {
                        PolicyNumber = policy.PolicyNumber,
                        AppliedDate = DateTime.Now,
                        Category = policy.Category,
                        PolicyType = policy.PolicyType,
                        Price = policy.Price,
                        CustomerId = customerId,
                    };
              
                    dbContext.AppliedPolicies.Add(appliedPolicy);
                    dbContext.SaveChanges();
                }
                else
                {
               
                }
            }
         
            return RedirectToAction("AppliedPolicies");
        }
        public ActionResult AppliedPolicies()   
        {
            List<AppliedPolicy> appliedPolicies;   

            using (var dbContext = new InsuranceDbContext())
            {
                
                appliedPolicies = dbContext.AppliedPolicies.ToList();
            }
            return View(appliedPolicies);
        }
        public ActionResult Categories()  
        {
            var categories = dbContext.Categories.ToList();
            return View(categories);
        }
        public ActionResult AskQuestion()   
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AskQuestion(QuestionView questionview)  
        {
            if (ModelState.IsValid)
            {
                int customerId = Convert.ToInt32(Session["CustomerUserId"]);
                Questions newQuestion = new Questions
                {
                    Question = questionview.Question,
                    Date = DateTime.Now,
                    Answer = questionview.Answer,
                    CustomerId = customerId
                };

                dbContext.Questions.Add(newQuestion);
                dbContext.SaveChanges();

                return RedirectToAction("Success");
            }

            return View(questionview);
        }
        public ActionResult Success() 
        {
            return View();
        }
        protected override void Dispose(bool disposing)   
        {
            if (disposing)
            {
                dbContext.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult AskCustomerId()
        {
            return View();
        }


        [HttpPost]
        public ActionResult DisplayQuestionsByCustomerId()  
        {
            int customerId = Convert.ToInt32(Session["CustomerUserId"]);
            if (customerId == null)
            {
                
                return RedirectToAction("Error");
            }
           
            var questions = dbContext.Questions.Where(q => q.CustomerId == customerId).ToList();
            ViewBag.CustomerId = customerId;
            return View(questions);
        }
    }
}

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
   
    <title></title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        
        .sidebar {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #343a40;
            padding-top: 20px;
            color: #fff;
        }

            .sidebar .profile-picture {
                background-color: aliceblue;
                width: 100px; 
                height: 100px; 
                border-radius: 50%; 
                display: block;
                margin: 0 auto;
                overflow: hidden; 
            }

            .sidebar a {
                padding: 10px 25px;
                text-decoration: none;
                font-size: 18px;
                color: #fff;
                display: block;
            }

                .sidebar a:hover {
                    background-color: #555;
                    transform: scale(1.05);
                }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout", "Validation")">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("AdminReg", "Validation")">Add new Admin</a>
                </li>

            </ul>
        </div>
    </nav>

    <div class="sidebar">
        <div class="profile-picture">
            <img src="~/Content/Admin.jpeg" alt="Profile Picture">
        </div>
        <h3 style="margin-left: 88px;">Admin</h3>
        <a href="@Url.Action("Dashboard", "Admin")">Dashboard</a>
        <a href="@Url.Action("GetAllCustomers", "Admin")">Customer</a>
        <a href="@Url.Action("Categories", "Admin")">Category</a>
        <a href="@Url.Action("Policy", "Admin")">Policy</a>


        <a href="@Url.Action("Question", "Admin")">Question</a>
    </div>

    <div id="ContentPlaceHolder2">
        @RenderBody() <!-- Render the content of the view here -->
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Shared/CustomerLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
    <title></title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .sidebar {
            height: 100%;
            width: 250px;
            position: fixed;
            top: 0;
            left: 0;
            background-color: #343a40;
            padding-top: 20px;
            color: #fff;
        }

            .sidebar .profile-picture {
                background-color: aliceblue;
                width: 100px; 
                height: 100px; 
                border-radius: 50%; 
                display: block;
                margin: 0 auto;
                overflow: hidden; 
            }

            .sidebar a {
                padding: 10px 25px;
                text-decoration: none;
                font-size: 18px;
                color: #fff;
                display: block;
            }

                .sidebar a:hover {
                    background-color: #555;
                    transform: scale(1.05);
                }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout", "Validation")">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="sidebar">
        <div class="profile-picture">
            <img src="~/Content/Customer.jpeg" alt="Profile Picture">
        </div>
        <h3 style="margin-left: 88px;">Customer</h3>
        <a href="@Url.Action("Dashboard", "Customer")" ">Dashboard</a>
        
        <a href="@Url.Action("ViewPoliciesToApply", "Customer")">Policy</a>


        <a href="@Url.Action("AskQuestion", "Customer")">Question</a>
    </div>

    <div id="ContentPlaceHolder2">
        @RenderBody() <!-- Render the content of the view here -->
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Insurance Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
    <style>
        #right-nav{
            display:none;
        }
        .navbar-nav .nav-link {
            padding: 10px 15px;
            transition: background-color 0.2s;
        }

            .navbar-nav .nav-link:hover {
                background-color: #333;
                
            }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

        /*.body-content {
            padding: 0px 0px 20px 0px;
            background-color: #f4f4f4;
        }*/

        .jumbotron {
            padding: 1rem 2rem;
        }

        footer {
            padding: 10px 0;
            background-color: #222;
            color: white;
            text-align: center;
        }

        /* Additional style for aligning items to the right */
        .navbar-nav {
            margin-left: auto;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Insurance Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Sign Up", "CustomerReg", "Validation", new { area = "" }, new { @class = "nav-link" })</li>

                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" id="loginDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Login
                        </a>
                        <div class="dropdown-menu" aria-labelledby="loginDropdown">
                            <a class="dropdown-item" href="@Url.Action("AdminLogin", "Validation")">Admin</a>
                            <a class="dropdown-item" href="@Url.Action("CustomerLogin", "Validation")">Customer</a>
                        </div>
                    </li>
                </ul>

                <ul id="right-nav" class="navbar-nav">
                    <li id="admin-dash">@Html.ActionLink("Dashboard", "Dashboard", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li id="cust-dash">@Html.ActionLink("Dashboard", "Dashboard", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li>@Html.ActionLink("Logout", "Logout", "Validation", new { area = "" }, new { @class = "nav-link" })</li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>