InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Models/PolicyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using DAL;

namespace UI.Models
{
    public class PolicyViewModel
    {
        [Required(ErrorMessage = "Policy Number is required")]
        public string PolicyNumber { get; set; }



        [Required(ErrorMessage = "Applied Date is required")]
        [DataType(DataType.Date)]
        public DateTime DateOfCreation { get; set; }

        public string Category { get; set; }
        public PolicyType PolicyType { get; set; }

        public double Price { get; set; }

    }


}

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Models/QuestionView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UI.Models
{
    public class QuestionView
    {

        public int QuestionId { get; set; }


        [MaxLength(255)] 
        public string Question { get; set; }

        [DataType(DataType.Date)]
        public DateTime Date { get; set; } = DateTime.Now; // Default to the current date

        [MaxLength(255)] 
        public string Answer { get; set; }

        [Required(ErrorMessage = "Customer Id is required.")]
        public int CustomerId { get; set; }
    }
}

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Controllers/AdminController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UI.Controllers
{
    
    public class AdminController : Controller
    {
        private InsuranceDbContext dbContext;
        public AdminController()
        {
            dbContext = new InsuranceDbContext(); //initialize your DbContext
        }
        // GET: Admin
        public ActionResult Dashboard()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                return View();
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }


        public ActionResult GetAllCustomers()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var customers = dbContext.Customers.ToList();
                return View(customers);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        //Action method to get all users
        public ActionResult GetAllUsers()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var users = dbContext.Customers.ToList();
                return View(users);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }


        public ActionResult PoliciesList()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var policies = dbContext.Policies.ToList();
                return View(policies);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult Categories()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var categories = dbContext.Categories.ToList();
                return View(categories);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult AllAppliedPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                // User is authenticated, proceed with the action
                var appliedPolicies = dbContext.AppliedPolicies.ToList();
                return View(appliedPolicies);
            }
            else
            {
                // User is not authenticated, redirect to login or unauthorized page
                return RedirectToAction("AdminLogin", "Validation");
            }
        }



        [HttpPost]
        public ActionResult ApprovePolicy(int policyId)
        {
            if (Session["AdminUserId"] != null)
            {
                var policy = dbContext.AppliedPolicies.Find(policyId);
                if (policy != null && policy.StatusCode == PolicyStatus.Pending)
                {
                    policy.StatusCode = PolicyStatus.Approved;
                    dbContext.SaveChanges();
                }
                return RedirectToAction("AllAppliedPolicies");
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        [HttpPost]
        public ActionResult DisapprovePolicy(int policyId)
        {
            if (Session["AdminUserId"] != null)
            {
                var policy = dbContext.AppliedPolicies.Find(policyId);
                if (policy != null && policy.StatusCode == PolicyStatus.Pending)
                {
                    policy.StatusCode = PolicyStatus.Disapproved;
                    dbContext.SaveChanges();
                }
                return RedirectToAction("AllAppliedPolicies");
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult ApprovedPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                var approvedPolicies = dbContext.AppliedPolicies.Where(p => p.StatusCode == PolicyStatus.Approved).ToList();
                return View(approvedPolicies);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult DisapprovedPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                var disapprovedPolicies = dbContext.AppliedPolicies.Where(p => p.StatusCode == PolicyStatus.Disapproved).ToList();
                return View(disapprovedPolicies);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult PendingPolicies()
        {
            if (Session["AdminUserId"] != null)
            {
                var pendingPolicies = dbContext.AppliedPolicies.Where(p => p.StatusCode == PolicyStatus.Pending).ToList();
                return View(pendingPolicies);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult Policy()
        {
            if (Session["AdminUserId"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }


        public ActionResult Question()
        {
            if (Session["AdminUserId"] != null)
            {
                var questions = dbContext.Questions.ToList();
                return View(questions);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        public ActionResult Reply(int id)
        {
            if (Session["AdminUserId"] != null)
            {
                var question = dbContext.Questions.Find(id);
                return View(question);
            }
            else
            {
                return RedirectToAction("AdminLogin", "Validation");
            }
        }

        [HttpPost]
        public ActionResult Reply(Questions model)
        {
            if (Session["AdminUserId"] != null && ModelState.IsValid)
            {
                var existingQuestion = dbContext.Questions.Find(model.QuestionId);
                if (existingQuestion != null)
                {
                    existingQuestion.Answer = model.Answer;
                    dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult SaveAnswer(int questionId, string answer)
        {
            if (Session["AdminUserId"] != null)
            {
                var existingQuestion = dbContext.Questions.Find(questionId);
                if (existingQuestion != null)
                {
                    existingQuestion.Answer = answer;
                    dbContext.SaveChanges();
                    return Json(new { success = true });
                }
            }

            return Json(new { success = false, error = "Question not found" });
        }


    }
}

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Controllers/PolicyController.cs
using DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UI.Models;

namespace UI.Controllers
{
    public class PolicyController : Controller
    {
        private InsuranceDbContext dbContext; 

        public PolicyController()
        {
            dbContext = new InsuranceDbContext(); 
        }

        public ActionResult ShowAllPolicy()
        {
            var policies = dbContext.Policies.ToList();

            return View(policies);
        }


        public ActionResult AddPolicy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPolicy(PolicyViewModel policyViewModel)
        {
            if (ModelState.IsValid)
            {
                
                Policy newPolicy = new Policy
                {
                    PolicyNumber = policyViewModel.PolicyNumber,
                    DateOfCreation = DateTime.Now,
                    Category = policyViewModel.Category,
                    PolicyType = policyViewModel.PolicyType,
                    Price = policyViewModel.Price
                };

                dbContext.Policies.Add(newPolicy);
                dbContext.SaveChanges();

                return RedirectToAction("AddPolicySuccess");
            }

            return View(policyViewModel);
        }
        public ActionResult AddPolicySuccess()
        {
            return View();
        }


        public ActionResult ShowAllPoliciesEdit()
        {
            List<Policy> allPolicies = dbContext.Policies.ToList();

            List<PolicyViewModel> viewModels = allPolicies.Select(policy => new PolicyViewModel
            {
                PolicyNumber = policy.PolicyNumber,
                DateOfCreation = policy.DateOfCreation,
                Category = policy.Category,
                PolicyType = policy.PolicyType,
                Price = policy.Price
            }).ToList();

            return View(viewModels);
        }


        public ActionResult EditPolicy(string policyNumber)
        {
            if (string.IsNullOrEmpty(policyNumber))
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            Policy policyToEdit = dbContext.Policies.FirstOrDefault(p => p.PolicyNumber == policyNumber);

            if (policyToEdit == null)
            {
                return HttpNotFound();
            }

            PolicyViewModel viewModel = new PolicyViewModel
            {
                PolicyNumber = policyToEdit.PolicyNumber,
                DateOfCreation = policyToEdit.DateOfCreation,
                Category = policyToEdit.Category,
                PolicyType = policyToEdit.PolicyType,
                Price = policyToEdit.Price
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPolicy(PolicyViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                Policy policyToEdit = dbContext.Policies.FirstOrDefault(p => p.PolicyNumber == viewModel.PolicyNumber);

                if (policyToEdit == null)
                {
                    return HttpNotFound();
                }

                policyToEdit.DateOfCreation = viewModel.DateOfCreation;
                policyToEdit.Category = viewModel.Category;
                policyToEdit.PolicyType = viewModel.PolicyType;
                policyToEdit.Price = viewModel.Price;
               
                dbContext.SaveChanges();

                return RedirectToAction("EditPolicySuccess");
            }
            return View(viewModel);
        }
        public ActionResult EditPolicySuccess()
        {
            return View();
        }


        public ActionResult ShowAllPoliciesDelete()
        {
            List<Policy> allPolicies = dbContext.Policies.ToList();
            List<PolicyViewModel> viewModels = allPolicies.Select(policy => new PolicyViewModel
            {
                PolicyNumber = policy.PolicyNumber,
                DateOfCreation = policy.DateOfCreation,
                Category = policy.Category,
                PolicyType = policy.PolicyType,
                Price = policy.Price
            }).ToList();

            return View(viewModels);
        }

        public ActionResult DeletePolicy(string policyNumber)
        {
            if (string.IsNullOrEmpty(policyNumber))
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            Policy policyToDelete = dbContext.Policies.FirstOrDefault(p => p.PolicyNumber == policyNumber);

            if (policyToDelete == null)
            {
                return HttpNotFound();
            }

            PolicyViewModel viewModel = new PolicyViewModel
            {
                PolicyNumber = policyToDelete.PolicyNumber,
                DateOfCreation = policyToDelete.DateOfCreation,
                Category = policyToDelete.Category,
                PolicyType = policyToDelete.PolicyType,
                Price = policyToDelete.Price
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmDeletePolicy(string policyNumber)
        {
            if (string.IsNullOrEmpty(policyNumber))
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }

            Policy policyToDelete = dbContext.Policies.FirstOrDefault(p => p.PolicyNumber == policyNumber);

            if (policyToDelete == null)
            {
                return HttpNotFound();
            }

            dbContext.Policies.Remove(policyToDelete);
            dbContext.SaveChanges();

            return RedirectToAction("DeletePolicySuccess");
        }

        public ActionResult DeletePolicySuccess()
        {
            return View();
        }

    }
}

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Admin/AllAppliedPolicies.cshtml
@using DAL
@model List<DAL.AppliedPolicy>

<style>
    body{
        background-color:lightgray;
    }
    .navbar-nav.flex-grow-1 {
        display: none;
    }

    #right-nav {
        display: block;
    }

    #cust-dash {
        display: none;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #343a40;
        color: white;
    }
    td {
        background-color: #8faebd;
    }
</style>

<table>
    <thead>
        <tr>
            <th>Policy Id</th>
            <th>Policy Number</th>
            <th>Customer Id</th>
            <th>Applied Date</th>
            <th>Category</th>
            <th>Policy Type</th>
            <th>Price</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var policy in Model)
            {
                <tr>
                    <td>@policy.AppliedPolicyId</td>
                    <td>@policy.PolicyNumber</td>
                    <td>@policy.CustomerId</td>
                    <td>@policy.AppliedDate.ToShortDateString()</td>
                    <td>@policy.Category</td>
                    <td>@policy.PolicyType</td>
                    <td>@policy.Price</td>
                    <td>
                        @switch (policy.StatusCode)
                        {
                            case PolicyStatus.Pending:<span>Pending</span>
                                break;

                            case PolicyStatus.Approved: <span>Approved</span>
                                break;

                            case PolicyStatus.Disapproved: <span>Disapproved</span>
                                break;

                            default: <span>Unknown</span>
                                break;
                        }

                    </td>

                    <td>
                        @if (policy.StatusCode == PolicyStatus.Pending)
                        {
                            using (Html.BeginForm("ApprovePolicy", "Admin", FormMethod.Post))
                            {
                                @Html.Hidden("policyId", policy.AppliedPolicyId)
                                <button type="submit" class="btn btn-outline-success">Approve</button>
                            }

                            using (Html.BeginForm("DisapprovePolicy", "Admin", FormMethod.Post))
                            {
                                @Html.Hidden("policyId", policy.AppliedPolicyId)
                                <button type="submit" class="btn btn-outline-danger">Disapprove</button>
                            }
                        }
                        else
                        {
                            <span class="badge badge-secondary">
                                @if (policy.StatusCode == PolicyStatus.Approved)
                                {
                                    <text>Approved</text>
                                }
                                else
                                {
                                    <text>Disapproved</text>
                                }
                            </span>
                        }
                    </td>
                </tr>
            }
    </tbody>
</table>

<script>
    function approvePolicy(policyId) {
        console.log("Disapproving policy with ID:" + policyId);
    }
</script>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Admin/ApprovedPolicies.cshtml
@model List<DAL.AppliedPolicy>
@{
    ViewBag.Title = "ApprovedPolicies";
}

<style>
    body{
        background-color:lightgray
    }
    h2{
        color: #007bff;
    }
    .navbar-nav.flex-grow-1 {
        display: none;
    }

    #right-nav {
        display: block;
    }

    #cust-dash {
        display: none;
    }

    table{
        width:100%;
        border-collapse: collapse;
        margin-top:20px;
        font-family: Arial, sans-serif;
        color: #333;
    }

    th,td {
        border: 1px solid #ddd;
        padding: 12px;
        text-align: left;
    }

    th {
        background-color: #343a40; 
        color: #fff; 
    }

    tbody tr:hover{
        background-color: #f5f5f5;
    }

    .status-approved{
        background-color: #28a745;
        color: #fff;
        padding: 8px 12px;
        border-radius: 4px;
    }
    td {
        background-color: #8faebd;
    }
</style>

<h2>Approved Policies</h2>
<table>
    <thead>
        <tr>
            <th>Policy Id</th>
            <th>Policy Number</th>
            <th>Customer Id</th>
            <th>Applied Date</th>
            <th>Category</th>
            <th>Policy Type</th>
            <th>Price</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var policy in Model)
            {
                <tr>
                    <td>@policy.AppliedPolicyId</td>
                    <td>@policy.PolicyNumber</td>
                    <td>@policy.CustomerId</td>
                    <td>@policy.AppliedDate.ToShortDateString()</td>
                    <td>@policy.Category</td>
                    <td>@policy.PolicyType</td>
                    <td>@policy.Price</td>
                    <td>
                        <span class="status-approved">Approved</span>
                    </td>
                </tr>
            }
    </tbody>
</table>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Admin/Categories.cshtml
@model List<DAL.Category>
<style>
    body {
        background-color: lightgray;
    }
    .navbar-nav.flex-grow-1{
        display:none;
    }
    #right-nav{
        display:block;
    }
    #cust-dash {
        display: none;
    }
    table {
        width: %;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #343a40;
        color: white;
    }

    td {
        background-color: #8faebd;
    }
    
</style>


<h2>List of Categories</h2>

<table>
    <tr>
        <th>Category ID</th>
        <th>Category Name</th>
    </tr>

    @foreach (var category in Model)
    {
        <tr>
            <td>@category.CategoryId</td>
            <td>@category.CategoryName</td>
        </tr>
    }
</table>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Admin/Dashboard.cshtml
@{ 
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    .content {
        margin-left: 270px;
        padding: 20px;
    }

    .form-group {
        margin-bottom:20px;
    }

    .form-group label {
        font-weight: bold;
    }

    .form-control {
        width: 100%;
        padding: 1px;
        border: 1px solid #ccc;
        border-radius: 4px;
        outline: none;
    }

    .card {
        width: 450px;
        background-color: lightgray;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s ease-in-out;
        margin-bottom: 20px;
    }
        .card:hover {
            transform: scale(1.05);
        }

    .card-title{
        color:black;
    }

    </style>
    

   <div class="content">
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("GetAllCustomers", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Total registered User </h5>
                        <br/> <br/>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("PoliciesList", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Listed Policies</h5>
                        <br /> <br />
                    </div>
                </div>
            </a>
        </div>
    </div>
    <br /> <br />

    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("Categories", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Listed Categories</h5>
                        <br /> <br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("Question", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Total Questions</h5>
                        <br /> <br />
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("AllAppliedPolicies", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Total Applied Policy Holder</h5>
                        <br /> <br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("ApprovedPolicies", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Approved Policy Holder</h5>
                        <br /> <br />
                    </div>
                </div>
            </a>
        </div>
    </div>
    <br /> <br />

    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("DisapprovedPolicies", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Disapproved Policy Holder</h5>
                        <br /> <br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("PendingPolicies", "Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Policy Holder Waiting For Approval</h5>
                        <br/> <br/>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Admin/GetAllCustomers.cshtml
@{
    ViewBag.Title = "GetAllCustomers";
}

﻿@model List<DAL.Customer>

<style>
    body{
        background-color:lightgray;
    }
    .navbar-nav.flex-grow-1 {
        display: none;
    }

    #right-nav {
        display: block;
    }

    #cust-dash {
        display: none;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #343a40;
        color: white;
    }
    td {
        background-color: #8faebd;
    }
</style>

<h2>All Customers</h2>

<table>
    <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>

    </tr>
    @foreach (var customer in Model)
    {
        <tr>
            <td>@customer.Id</td>
            <td>@customer.FirstName</td>
            <td>@customer.LastName</td>

        </tr>
    }
</table>

InsuranceManagementSystem/InsuranceManagementSystem/InsuranceManagementSystem/UI/Views/Admin/Policy.cshtml
@{
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    .content {
        margin-left: 270px;
        padding: 20px;
    }

    .form-group {
        margin-bottom: 20px;
    }

        .form-group label {
            font-weight: bold;
        }

    .form-control {
        width: 100%;
        padding: 1px;
        border: 1px solid #ddd;
        border-radius: 5px;
        outline: none;
    }

    .card {
        width: 450px;
        background-color: lightgray;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        transition: transform 0.2s ease-in-out;
        margin-bottom: 20px;
    }

        .card:hover {
            transform: scale(1.05);
        }

    .card-title {
        color: black;
    }
    td {
        background-color: #8faebd;
    }
</style>
<div class="content">
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("PoliciesList","Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">View Policy</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("AddPolicy","Policy")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Add Policy</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("ShowAllPoliciesEdit","Policy")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Update Policy</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("ShowAllPoliciesDelete","Policy")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Delete Policy</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("AllAppliedPolicies","Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Total Applied Policy Holder</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("ApprovedPolicies","Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Approved Policy Holder</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
    </div>
    <br /><br />
    <div class="row">
        <div class="col-md-6">
            <a href="@Url.Action("DisapprovedPolicies","Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Disapproved Policy Holder</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6">
            <a href="@Url.Action("PendingPolicies","Admin")">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Policy Holder Waiting For Approval</h5>
                        <br /><br />
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>